In [1]:
#IMPORT LIBRARIES
import pandas as pd
import numpy as np

In [2]:
#IMPORT DATA
claimants=pd.read_csv("C:\\Users\\PRIYANKA\\Downloads\\claimants (1).csv")
claimants

CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

In [3]:
#3.DATA UNDERSTANDING
claimants.shape

(1340, 7)

In [4]:
claimants.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [5]:
claimants.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [6]:
claimants.describe()

CASENUM     ATTORNEY       CLMSEX     CLMINSUR     SEATBELT  \
count   1340.000000  1340.000000  1328.000000  1299.000000  1292.000000   
mean   11202.001493     0.488806     0.558735     0.907621     0.017028   
std     9512.750796     0.500061     0.496725     0.289671     0.129425   
min        0.000000     0.000000     0.000000     0.000000     0.000000   
25%     4177.000000     0.000000     0.000000     1.000000     0.000000   
50%     8756.500000     0.000000     1.000000     1.000000     0.000000   
75%    15702.500000     1.000000     1.000000     1.000000     0.000000   
max    34153.000000     1.000000     1.000000     1.000000     1.000000   

            CLMAGE         LOSS  
count  1151.000000  1340.000000  
mean     28.414422     3.806307  
std      20.304451    10.636903  
min       0.000000     0.000000  
25%       9.000000     0.400000  
50%      30.000000     1.069500  
75%      43.000000     3.781500  
max      95.000000   173.604000

In [7]:
#4.DATA PREPARATION

In [8]:
del claimants['CASENUM']

In [9]:
claimants.head()

ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0         0     0.0       1.0       0.0    50.0  34.940
1         1     1.0       0.0       0.0    18.0   0.891
2         1     0.0       1.0       0.0     5.0   0.330
3         0     0.0       1.0       1.0    31.0   0.037
4         1     0.0       1.0       0.0    30.0   0.038

In [10]:
claimants.dropna(axis=0,inplace=True)

In [11]:
claimants.shape

(1096, 6)

In [12]:
claimants.isna().sum()

ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [13]:
claimants.dtypes

ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [14]:
#5.MODEL BUILDING

In [15]:
X=claimants.drop(labels='ATTORNEY',axis=1)
y=claimants[['ATTORNEY']]

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,Y_test=train_test_split(X,y,test_size=0.20,random_state=None,shuffle=True)

In [17]:
X_train.shape,y_train.shape

((876, 5), (876, 1))

In [18]:
X_train

CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
740      1.0       1.0       0.0    70.0   0.035
671      1.0       1.0       0.0    55.0   0.030
641      0.0       1.0       0.0    45.0   3.900
208      1.0       1.0       0.0    37.0  15.816
1097     1.0       1.0       0.0    65.0   4.558
...      ...       ...       ...     ...     ...
793      0.0       1.0       0.0     6.0   0.530
587      1.0       1.0       0.0    70.0   3.780
1135     1.0       1.0       0.0    57.0   3.915
198      0.0       1.0       0.0    49.0   0.390
1064     1.0       1.0       0.0    14.0   1.650

[876 rows x 5 columns]

In [19]:
y_train

ATTORNEY
740          0
671          1
641          0
208          0
1097         1
...        ...
793          0
587          0
1135         1
198          0
1064         0

[876 rows x 1 columns]

In [20]:
#6.MODEL BUILDING

In [21]:
from sklearn.linear_model import LogisticRegression
logistic_model=LogisticRegression()
logistic_model.fit(X_train,y_train)




C:\Users\PRIYANKA\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [22]:
logistic_model.coef_

array([[ 0.44087588,  0.42371879, -0.39600072,  0.00751275, -0.35354456]])

In [23]:
logistic_model.intercept_

array([-0.13848069])

In [25]:
#7.Model Testing

#TRAINING DATA

y_pred_train=logistic_model.predict(X_train)
y_pred_train

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,

In [31]:
# TEST DATA
y_pred_test= logistic_model.predict(X_train)
y_pred_test

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,

In [33]:
#8 MODEL EVALUATION

from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_pred_train)

0.7009132420091324

In [34]:
#9.MODEL DEPLOYMENT

In [35]:
from pickle import dump

In [37]:
dump(logistic_model,open('log_model.pkl','wb'))

In [38]:
from pickle import load

In [42]:
loaded_logistic_model=load(open('log_model.pkl','rb'))
loaded_logistic_model

LogisticRegression()

In [44]:
y_prediction_validation=loaded_logistic_model.predict(X_test)
y_prediction_validation

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1],
      dtype=int64)